TestWithValue.Web/Controllers/CartController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using TestWithValue.Application.AllServicesAndInterfaces.Services_Interface;
using TestWithValue.Application.AllServicesAndInterfaces.Services_Interface.OperationResult__s_Interface;
using TestWithValue.Domain.OperationResult;
using TestWithValue.Domain.ViewModels.CartItem;
using TestWithValue.Domain.ViewModels.Topic;

namespace TestWithValue.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartItemService _cartItemService;
        private readonly IMapper _mapper;
        private readonly IOperationResultService _operationResultService;


       public CartController(ICartItemService cartItemService,IMapper mapper, IOperationResultService operationResultService)
        {
            _cartItemService = cartItemService;
            _mapper = mapper;
            _operationResultService = operationResultService;
                
        }
        public IActionResult Index()
        {
            return View();
        }
        // افزودن به سبد خرید
        [HttpPost]
        public async Task<IActionResult> AddToCart([FromBody] AddRequestVM addRequest)
        {
            try
            {
                var userId = 1; // در واقع این باید از لاگین کاربر گرفته شود
                var cartItemVM = new CartItemViewModel()
                {
                    TopicId = addRequest.TopicId,
                    UserId = userId
                };

                await _cartItemService.AddToCart(cartItemVM);

                //var operationResultMessage = _operationResultService.OperationResultMethod().Message;
                //TempData["OperationResult"] = JsonConvert.SerializeObject(_operationResultService.OperationResultMethod());
                TempData["OperationResult"] = JsonConvert.SerializeObject(_operationResultService.OperationResultMethod());


                return Ok(); // به جای RedirectToAction
            }
            catch (Exception ex)
            {
                // ثبت خطا و ارسال پیغام خطا به کلاینت
                return StatusCode(500, new { error = ex.Message });
            }
        }


        [HttpPost]
        public async Task<IActionResult> RemoveFromCart(int cartItemId)
        {
            await _cartItemService.RemoveFromCart(cartItemId);

            //var operationResultMessage = _operationResultService.OperationResultMethod().Message;
            //TempData["OperationResult"] = JsonConvert.SerializeObject(_operationResultService.OperationResultMethod());

            TempData["OperationResult"] = JsonConvert.SerializeObject(_operationResultService.OperationResultMethod());


            return RedirectToAction("ShowCart");
        }
        [HttpGet]
        public async Task<IActionResult> ShowCart()
        {
            var operationResultJson = TempData["OperationResult"] as string;
            if (!string.IsNullOrEmpty(operationResultJson))
            {
                var operationResult = JsonConvert.DeserializeObject<OperationResult>(operationResultJson);
                ViewBag.OperationResult = operationResult;
            }
            var userId = 1; // در واقع این باید از لاگین کاربر گرفته شود
            var cartItems = await _cartItemService.GetCartItemsByUserId(userId);
            var cartItemVMs = cartItems.Select(item => new CartItemViewModel
            {
                CartItemId = item.CartItemId,
                     TopicId=item.TopicId ,
                TopicName = item.Topic.TopicName,

                
            }).ToList();
            return View(cartItemVMs);
        }


    }
}

TestWithValue.Web/Controllers/QuizController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections;
using TestWithValue.Application.AllServicesAndInterfaces.Services_Interface;
using TestWithValue.Application.AllServicesAndInterfaces.Services_Interface.ActionMessage_s_Interface;
using TestWithValue.Domain.ViewModels.Answer;
using TestWithValue.Domain.ViewModels.Option;
using TestWithValue.Domain.ViewModels.Question;
using TestWithValue.Domain.ViewModels.Result;

namespace TestWithValue.Web.Controllers
{
    public class QuizController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IQuestionService _questionService;
        private readonly ITestService _testService;
        private readonly IOptionService _optiontService;
        private readonly IAnswerService _answerService;
        private readonly ITopicSevice _topicService;
        private readonly IActionMessageService _actionMessageService;


        public QuizController(IQuestionService questionService, IOptionService optionService, ITestService testService, IAnswerService answerService,ITopicSevice topicSevice, IMapper mapper,IActionMessageService actionMessageService)
        {
            _mapper = mapper;
            _questionService = questionService;
            _testService = testService;
            _optiontService = optionService;
            _answerService = answerService; 
            _topicService = topicSevice;
            _actionMessageService = actionMessageService;   
        }

        public async Task<IActionResult> Start()
        {
            _actionMessageService.AddMessage("به صفحه آزمون خوش امدید", "success");

            var tests = await _testService.GetAllTests();
            return View(tests);
        }

        // دریافت سوالات
        [HttpGet]
        public async Task<IActionResult> ShowQuestions(int index, int testId)
        {
            var questions = await _questionService.GetQuestionsByTestId(testId);
            var questionsList = questions.ToList();

            // اطمینان از اینکه ایندکس معتبر است
            if (index < 0 || index >= questionsList.Count)
            {
                return NotFound();
            }

            // یافتن سوال فعلی بر اساس ایندکس
            var currentQuestion = questionsList[index];

            // دریافت گزینه‌ها برای سوال فعلی
            var options = await _optiontService.GetOptionByQuestionIdAndTestId(currentQuestion.QuestionId, testId);

            var viewModel = new ShowQuestionsWithSelectedOptionViewModel
            {
                QuestionId = currentQuestion.QuestionId,
                QuestionText = currentQuestion.QuestionText,
                CurrentQuestionIndex = index,
                Options = options,
                IsLastQuestion = index == questionsList.Count - 1,
                TestId = testId
            };
            ViewBag.TotalQuestions = questionsList.Count;

            return View(viewModel);


            //return View();
        }




        [HttpPost]
        public async Task<IActionResult> SaveAnswer([FromBody] AnswerViewModel model)
        {
            

            if (ModelState.IsValid)
            {
                model.UserId = 1; // دریافت UserId کاربر از context یا session


                var existingAnswer = await _answerService.GetAnswerByQuestionId(model.QuestionId);

                if (existingAnswer != null)
                {
                   // اگر پاسخی از قبل وجود دارد، آن را آپدیت کنید
                  existingAnswer.AnswerValue = model.AnswerValue;
                  existingAnswer.OptionId = model.OptionId;

                   await _answerService.UpdateAnswer(existingAnswer);
                }
                else
                {
                    // اگر پاسخی وجود ندارد، پاسخ جدید ایجاد کنید
                    await _answerService.SaveAnswer(model);
                }

                return Ok();
            }

            return BadRequest();
        }
        [HttpGet]
        public async Task<IActionResult> GetAnswer(int questionId, int testId)
        {
            // استفاده از سرویس برای دریافت پاسخ بر اساس questionId و testId
            var answer = await _answerService.GetAnswerByQuestionId(questionId);

            // بررسی اینکه آیا پاسخی پیدا شده است یا خیر
            if (answer == null)
            {
                return NotFound(); // یا می‌توانید مقدار پیش‌فرضی برگردانید
            }

            // برگرداندن پاسخ به صورت JSON
            return Json(answer); // یا return Ok(answer); نیز می‌تواند استفاده شود
        }
        // پایان آزمون و نمایش نتیجه
        public async Task<IActionResult> ShowResult(int testId)
        {
            var userId = 1;
            var answers = await _answerService.GetAnswerByTestIdAndUserId(testId, userId);
            if (answers != null)
            {
                // محاسبه مجموع امتیازات
                int totalScore = answers.Sum(a => a.AnswerValue);
                var topics = await _topicService.GetTopicByTestId(testId, totalScore);
                var topicsVM = new ShowResultViewModel
                {
                    Topics = topics
                };
                return View(topicsVM);
            }

            return BadRequest();

        }

        // هدایت پس از اتمام زمان آزمون
        public IActionResult Timeout()
        {
            return RedirectToAction("Start");
        }
    }
}

TestWithValue.Web/ViewComponents/ActionMessageViewComponent/ActionMessageViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TestWithValue.Application.AllServicesAndInterfaces.Services_Interface.ActionMessage_s_Interface;

namespace TestWithValue.Web.ViewComponents.ActionMessageViewComponent
{
    public class ActionMessageViewComponent : ViewComponent
    {
        private readonly IActionMessageService _actionMessageService;

        public ActionMessageViewComponent(IActionMessageService actionMessageService)
        {
            _actionMessageService = actionMessageService;
        }

        public IViewComponentResult Invoke()
        {
            var messages = _actionMessageService.GetMessages();
            return View("/Views/Shared/Components/ActionMessage/Default.cshtml",messages);
        }
    }
}

TestWithValue.Web/Views/Quiz/ShowQuestions.cshtml
@using TestWithValue.Domain.ViewModels.Question

@model ShowQuestionsWithSelectedOptionViewModel

<div id="questionContainer">
    <!-- نمایش متن سوال -->
    <p>@Model.QuestionText</p>

    <form id="quizForm" method="post">
        <div>
            @foreach (var option in Model.Options)
            {
                <div>
                    <input type="radio" name="answer" value="@option.Value" id="option-@option.OptionId" data-optionid="@option.OptionId" />
                    <label for="option-@option.OptionId">@option.OptionText</label>
                </div>
            }
        </div>

        <!-- ارسال شناسه سوال به صورت hidden -->
        <input type="hidden" name="questionId" value="@Model.QuestionId" />
        <input type="hidden" name="testId" value="@Model.TestId" />
    </form>


    <!-- دکمه‌های قبلی و بعدی -->
    <div>
        @if (Model.CurrentQuestionIndex > 0)
        {
            <button id="previousQuestion" onclick="loadQuestion(@Model.CurrentQuestionIndex - 1, @Model.TestId)">سوال قبلی</button>
        }

        @if (Model.CurrentQuestionIndex < @ViewBag.TotalQuestions - 1)
        {
            <button id="nextQuestion" onclick="submitAndLoadNextQuestion(@Model.CurrentQuestionIndex + 1, @Model.TestId)">سوال بعدی</button>
        }
        else
        {
            <!-- دکمه ثبت نهایی و مشاهده نتیجه در سوال آخر -->
            <button id="submitQuiz" onclick="submitQuiz(@Model.TestId)">ثبت جواب سوالات و دیدن نتیجه آزمون</button>
        }

    </div>
</div>
<div>
    <span id="timer"></span> <!-- تایمر -->
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
@section Scripts {

    <script>
        // بررسی وجود زمان باقی‌مانده در localStorage
        var timerDuration = localStorage.getItem('timerDuration') ? parseInt(localStorage.getItem('timerDuration')) : 10 * 60;

        if (window.location.pathname !== '@Url.Action("ShowResult", "Quiz")') {
            var countdownTimer = setInterval(function () {
                var minutes = Math.floor(timerDuration / 60);
                var seconds = timerDuration % 60;
                document.getElementById('timer').innerText = minutes + ":" + (seconds < 10 ? "0" : "") + seconds;

                // ذخیره زمان باقی‌مانده در localStorage
                localStorage.setItem('timerDuration', timerDuration);

                if (timerDuration <= 0) {
                    clearInterval(countdownTimer);
                    localStorage.removeItem('timerDuration'); // حذف زمان پس از پایان
                    window.location.href = '@Url.Action("Start", "Quiz")'; // هدایت پس از پایان زمان
                }

                timerDuration--;
            }, 1000);
        }


        // ارسال پاسخ و بارگذاری سوال بعدی
        function loadQuestion(index, testId) {
            // ابتدا سوال را بارگذاری می‌کنیم
            $.ajax({
                url: '@Url.Action("ShowQuestions", "Quiz")',
                type: 'GET',
                data: { index: index, testId: testId }, // پاس دادن testId
                success: function (result) {
                    $('#questionContainer').html(result);

                    // پس از بارگذاری موفق سوال، questionId جدید را از فرم گرفته و سپس پاسخ را بارگذاری می‌کنیم
                    var questionId = $('input[name="questionId"]').val();

                    // سپس پاسخ قبلی را بارگذاری می‌کنیم
                    $.ajax({
                        url: '@Url.Action("GetAnswer", "Quiz")',
                        type: 'GET',
                        data: { questionId: questionId, testId: testId }, // پاس دادن testId به همراه questionId
                        success: function (data) {
                            // بررسی می‌کنیم آیا کاربر پاسخی داده است یا خیر
                            if (data && data.optionId) {
                                // پیدا کردن گزینه مربوطه و تیک زدن آن
                                $('#option-' + data.optionId).prop('checked', true);
                            }
                        }
                    });
                },
                error: function () {
                    alert('خطا در بارگذاری سوال');
                }
            });
        }

        function submitAndLoadNextQuestion(index, testId) {
            // ارسال پاسخ فعلی و بارگذاری سوال بعدی
            var questionId = $('input[name="questionId"]').val();
            var selectedOptionId = $('input[name="answer"]:checked').data('optionid');
            var selectedOptionValue = $('input[name="answer"]:checked').val();

            if (!selectedOptionId) {
                alert('لطفا یک گزینه را انتخاب کنید!');
                return;
            }


            var answerData = {
                questionId: questionId,
                optionId: selectedOptionId,
                testId: testId,
                AnswerValue: selectedOptionValue
            };

            $.ajax({
                url: '@Url.Action("SaveAnswer", "Quiz")',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify(answerData),
                success: function () {
                    loadQuestion(index, testId); // بارگذاری سوال بعدی
                },
                error: function () {
                    alert('خطایی در ثبت پاسخ رخ داد!');
                }
            });
        }

        // ارسال نهایی و مشاهده نتیجه آزمون
        function submitQuiz(testId) {
            var questionId = $('input[name="questionId"]').val();
            var selectedOptionId = $('input[name="answer"]:checked').data('optionid');
            var selectedOptionValue = $('input[name="answer"]:checked').val();

            if (!selectedOptionId) {
                alert('لطفا یک گزینه را انتخاب کنید!');
                return;
            }

            var answerData = {
                questionId: questionId,
                optionId: selectedOptionId,
                testId: testId,
                AnswerValue: selectedOptionValue
            };

            // ارسال داده‌ها به صورت JSON
            $.ajax({
                url: '@Url.Action("SaveAnswer", "Quiz")',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify(answerData),
                success: function () {
                    // پس از ثبت موفق، تایمر را متوقف کرده و localStorage را پاک کنید
                    clearInterval(countdownTimer);
                    localStorage.removeItem('timerDuration');

                    // سپس به صفحه نتیجه هدایت شوید
                    window.location.href = '@Url.Action("ShowResult", "Quiz")' + '?testId=' + testId;
                },
                error: function () {
                    alert('خطایی در ثبت پاسخ رخ داد!');
                }
            });
        }


    </script>
}

 

@* @await Component.InvokeAsync("ShowQuestions", new { index = Model.CurrentQuestionIndex, testId = Model.TestId })
 *@

TestWithValue.Web/Views/Quiz/ShowResult.cshtml
@using TestWithValue.Domain.ViewModels.Result
@model ShowResultViewModel



<div class="topics-container">
    @foreach (var topic in Model.Topics)
    {
        <div class="card">
            <h3>@topic.TopicName</h3>
            <!-- ارسال topicId و testId به متد addToCart -->
            <button onclick="addToCart(@topic.TopicId)">افزودن به سبد خرید</button>
        </div>
    }
</div>

@section Scripts {
    <script>
        function addToCart(topicId) {
            console.log("Sending Topic ID:", topicId); // برای بررسی اینکه topicId ارسال می‌شود

            var data = {
                topicId: topicId
            };

            $.ajax({
                url: '@Url.Action("AddToCart", "Cart")',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify(data),
                success: function (response) {
                    // پس از موفقیت به صفحه ShowCart هدایت شو
                    window.location.href = '@Url.Action("ShowCart", "Cart")';
                },
                error: function (xhr) {
                    console.log("خطا در افزودن به سبد خرید:", xhr.responseText);
                }
            });

        }
      
    </script>
}

TestWithValue.Web/Views/Quiz/Start.cshtml
@using TestWithValue.Domain.ViewModels.Test
@model IEnumerable<ShowTestViewModel>
@{
    ViewData["Title"] = "Start";
}


@await Component.InvokeAsync("ActionMessage")


<h2>لیست آزمون‌ها</h2>
<ul>
    @foreach (var test in Model)
    {
        <li>
            <a href="@Url.Action("ShowQuestions", "Quiz", new { testId=test.TestId })">@test.TestName</a>
        </li>
    }
</ul>